site_name: 'Support Democracy'
docs_dir: '../../docs/tr'                           # Where to find the English markdown files
site_dir: '../../generated/tr'                      # Where to put the English HTML files
site_url: 'https://muratkendir.github.io/supportdemocracy/tr/'

theme:
    name: material
    custom_dir: '../../overrides/'                  # This is where the customization of the theme lives
    logo: assets/images/logo.svg                    # The logo is shared by all languages
    favicon: assets/images/favicon.ico              # The favicon is shared by all languages
    language: tr                                    # The build's language

extra_css:
  - assets/stylesheets/yesplan.css                  # CSS is shared by all languages

extra:                                              # Language Selection
  alternate:  

      # Switch to English
    - name: English
      link: /en/
      lang: en

    # Switch to Turkish
    - name: Turkish
      link: /tr/
      lang: tr

    # Switch to German
    - name: Deutsch
      link: /de/
      lang: de

plugins:
  - search:                                         
      lang: 
        - tr                                      # Set language for search
  - tags

nav:
- Merhaba: index.md
